export const style = {
	title_frame: {
		boxSizing: 'border-box',
		background: '#F7F8FC',
		borderWidth: '0px 0px 1px 0px',
		padding: '0px',
		width: '1050px',
		height: '48px',
	},
	title_table: {
		display: 'flex',
		width: '1050px',
		overflowX: 'hidden',
	},
	title_weeks: {
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
		minWidth: '154px',
		height: '24px',
		borderWidth: '0px 1px 1px 0px',
		fontWeight: '400',
		fontSize: '12px',
		lineHeight: '16px',
		padding: 0,
	},
	title_days: {
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
		minWidth: '22px',
		height: '24px',
		borderWidth: '0px 1px 0px 0px',
		fontWeight: '400',
		fontSize: '12px',
		lineHeight: '16px',
		padding: 0,
	},
}